on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@v2
        if: failure() || cancelled()
        env:
          SLACK_COLOR: "#FF0000"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: robocop
          SLACK_TITLE: Commit Message
          SLACK_ICON: https://github.com/tvofik.png?size=48
          SLACK_FOOTER: Company Name

      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: robocop
          SLACK_TITLE: Commit Message
          SLACK_ICON: https://github.com/tvofik.png?size=48
          SLACK_FOOTER: Company Name
