on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: mainu
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@v2
        if: failure() || cancelled()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#DF5A49"
          SLACK_USERNAME: robocop
          SLACK_ICON: https://github.com/tvofik.png?size=48
          SLACK_FOOTER: Company Name

      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: robocop
          SLACK_ICON: https://github.com/tvofik.png?size=48
          SLACK_FOOTER: Company Name
